### PR TITLE
Typescriptify all of the UI peripherals

### PR DESCRIPTION
**Pull request by iflan**
This converts the audio, gamepad, keyboard, printer, and tape
peripherals into Typescript. This is a pretty mechanical change.

It does fix issue #72, though.

### CODE REVIEW

**Comment by whscullin** [comment]
What's here looks good, but I think there are a couple missing files.

**Comment by iflan** [comment]
Updated. Sorry about that!

**Comment by whscullin** [comment]
Some day I will be brave and re-factor ui/apple2.js. I've made at least two false starts.

**Comment by iflan** [comment]
I just sent PR #74 which is not a refactor, but will probably make it easier to refactor. :-)

**Pull request merged**
