### PR TITLE
Fix issue #187 (and upgrade jest)

### PR DESCRIPTION
**Pull request by iflan**
Before, `mmu.ts` and `cards/langcard.ts` would deactivate
writing to the language card if `prewrite` was reset.  However,
it is totally possible to reset `prewrite` and leave writing enabled,
as shown my Sather in _Understanding the Apple II_, table 5.4, p. 5-30, 
and _Understanding the Apple IIe_, table 5.5, p. 5-24.  For example:

```assembly_x86
    sta  $c08a  ; WRITE DISABLE; READ DISABLE
    lda  $c08b  ; PRE-WRITE set
    lda  $c08b  ; WRITE enabled
    sta  $c08a  ; PRE-WRITE reset; WRITE still enabled!
    lda  $c08b  ; PRE-WRITE set; WRITE still enabled!
```

would not work correctly because the last line would clear `_writebsr`
before setting `_prewrite`, which is incorrect.

Now, `_writebsr` is only set when `_prewrite` is set and thus only
cleared when `writeSwitch` is false. 

There is also a new test for the `MMU` and `LanuageCard` classes.

### CODE REVIEW

**Comment by whscullin** [comment]
Sorry I haven't had a chance to look more closely at this, but one thing to consider is that the //e language card logic is a clone of the the code in cards/language, so it might be necessary to update that too? Possibly we should consolidate that logic somewhere?

**Comment by iflan** [comment]
Good point. There is code in `cards/langcard.ts` that does the same thing and has the same bug. I'll try to fix that and add a test as well. It's likely that we can consolidate the logic, but I'll do that in another future change.

**Comment by iflan** [comment]
OK—the latest commit fixes the language card on the Apple II as well. In both cases, the test that repros the bug report in #187 fails unless the fix is applied.

**Review by whscullin — APPROVED** [review]
LGTM

**Comment by whscullin** [comment]
Weirdly, this works with npm 8.x, (which I have on my machine) but fails with npm 9.x (which is on the machine hosting scullinsteel.com):
```
pm ERR! Could not resolve dependency:
npm ERR! peer jest@">=20 <=27" from jest-image-snapshot@4.5.1
npm ERR! node_modules/jest-image-snapshot
npm ERR!   dev jest-image-snapshot@"^4.5.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: jest@27.5.1
npm ERR! node_modules/jest
npm ERR!   peer jest@">=20 <=27" from jest-image-snapshot@4.5.1
npm ERR!   node_modules/jest-image-snapshot
npm ERR!     dev jest-image-snapshot@"^4.5.1" from the root project
```

**Comment by whscullin** [comment]
Updating `jest-image-snapshot` resolves that. We were a couple major versions behind but I did't encounter any issues updating.

**Pull request merged**
